name: neatdart
description: NEAT is a method developed by Kenneth O. Stanley for evolving arbitrary neural networks. NEAT-Dart is a pure Dart implementation of NEAT, with no dependencies other than the Dart standard library.
version: 1.0.0
repository: https://github.com/gongxiancao/neatdart

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
